/**
 * `ark token` -- inspect / rotate / list bearer tokens.
 *
 * Local mode: the token is the per-install file at `<arkDir>/arkd.token`,
 * generated by the daemon at first boot. `ark token` prints it, `ark token
 * rotate` regenerates it (atomic rename + 0o600), and `ark token list` shows
 * the file path with mode + mtime.
 *
 * Hosted mode: the local file is the operator's master token and must NOT be
 * handed to end users. `ark token` and `ark token rotate` both fail with a
 * friendly error pointing the caller at the web UI / `ark login`. `ark token
 * list` falls through to the existing apiKey RPC (tenant-scoped, never
 * returns key values).
 */

import type { Command } from "commander";
import chalk from "chalk";
import { chmodSync, existsSync, readFileSync, renameSync, statSync, writeFileSync } from "fs";
import { join } from "path";
import { randomBytes } from "crypto";

const arkdTokenPath = (arkDir: string): string => join(arkDir, "arkd.token");

export function registerTokenCommand(program: Command): void {
  const token = program.command("token").description("Manage Ark bearer tokens");

  // ── ark token (default = show) ────────────────────────────────────────────
  token
    .command("show", { isDefault: true })
    .description("Print the local bearer token (treat the output as a secret)")
    .action(async () => {
      const { loadConfig } = await import("../../core/config.js");
      const cfg = loadConfig();
      const path = arkdTokenPath(cfg.dirs.ark);

      // Hosted-mode misuse guard: the on-disk arkd.token is the operator's
      // master key, not an end-user credential. Refuse to print it before any
      // file read so a misconfigured CLI cannot leak it via stdout capture.
      if (cfg.authSection.requireToken) {
        console.error(
          chalk.red(
            "Hosted mode detected (auth.requireToken=true). The local arkd.token\n" +
              "is the operator's master token, not yours. Use the web UI or\n" +
              "`ark login` to manage your personal API tokens.",
          ),
        );
        process.exit(1);
      }

      if (!existsSync(path)) {
        console.error(
          chalk.red(`No token at ${path}. Start the daemon once (\`ark server daemon start\`) to generate one.`),
        );
        process.exit(1);
      }

      const value = readFileSync(path, "utf-8").trim();
      console.log(value);
    });

  // ── ark token rotate ──────────────────────────────────────────────────────
  token
    .command("rotate")
    .description("Generate a new local bearer token (local mode only). Invalidates the previous one.")
    .action(async () => {
      const { loadConfig } = await import("../../core/config.js");
      const cfg = loadConfig();
      if (cfg.authSection.requireToken) {
        console.error(chalk.red("Hosted mode: rotate via the web UI / api_keys endpoint instead."));
        process.exit(1);
      }

      const path = arkdTokenPath(cfg.dirs.ark);
      const fresh = randomBytes(32).toString("base64url");

      // Atomic write: write to a temp file, then rename. Prevents a crash
      // mid-write from leaving the daemon with an unreadable token file.
      const tmp = `${path}.tmp`;
      writeFileSync(tmp, fresh, { mode: 0o600 });
      // writeFileSync's mode arg is honored only on file creation; chmod
      // explicitly so umask-stripped bits get reasserted.
      chmodSync(tmp, 0o600);
      renameSync(tmp, path);

      console.log(chalk.green("Token rotated. Restart the daemon to pick up the new value."));
      console.log(fresh);
    });

  // ── ark token list ────────────────────────────────────────────────────────
  token
    .command("list")
    .description("List tokens. Local: the on-disk arkd.token. Hosted: your API tokens (no values).")
    .option("--tenant <tenantId>", "Tenant ID (hosted mode)", "default")
    .action(async (opts: { tenant: string }) => {
      const { loadConfig } = await import("../../core/config.js");
      const cfg = loadConfig();

      // Local mode: a single on-disk file. Print metadata only; the contents
      // are still considered a secret and must be fetched via `ark token`.
      if (!cfg.authSection.requireToken) {
        const path = arkdTokenPath(cfg.dirs.ark);
        if (!existsSync(path)) {
          console.error(chalk.red(`No local token at ${path}.`));
          process.exit(1);
        }
        const stat = statSync(path);
        const mode = (stat.mode & 0o777).toString(8).padStart(3, "0");
        console.log(`local: ${path}   (mode 0${mode}, modified ${stat.mtime.toISOString()})`);
        return;
      }

      // Hosted mode: dispatch to the existing apiKey/list RPC. Values are
      // never exposed by the server so this surface is safe to print.
      const { getArkClient } = await import("../app-client.js");
      const ark = await getArkClient();
      const keys = await ark.apiKeyList(opts.tenant);
      if (!keys.length) {
        console.log(chalk.dim("No API keys found."));
        return;
      }
      console.log(chalk.bold(`API keys for tenant: ${opts.tenant}`));
      console.log();
      for (const k of keys) {
        const lastUsed = k.last_used_at ? `last used ${k.last_used_at}` : "never used";
        console.log(`  ${k.id.padEnd(14)} ${k.name.padEnd(20)} ${k.role.padEnd(8)} ${lastUsed}`);
      }
    });
}
