// AUTO-GENERATED by scripts/inject-version.ts -- DO NOT EDIT.
// Regenerated from package.json on every `make build-cli` and in the
// release.yml `build-ark` job before `bun build --compile`. Baking the
// version into a TS constant avoids runtime __dirname / package.json reads
// that do not work in compiled binaries.
export const VERSION = "0.21.33";
