/**
 * inject-version.ts -- generate packages/core/version.ts from package.json.
 *
 * Run before `bun build --compile` so the compiled binary bakes the correct
 * version string into its bundle. Avoids the runtime file-read that used to
 * live in `packages/core/infra/update-check.ts` (which broke in compiled
 * binaries because `__dirname` pointed into Bun's virtual FS, and because
 * `package.json` is not shipped in the release tarball).
 *
 * Dev mode: `./ark --version` runs via `bun run` which bundles
 * `version.ts` as source; the file is re-generated on every build-cli.
 *
 * Run from the repo root:
 *   bun run scripts/inject-version.ts
 *
 * Writes: packages/core/version.ts (gitignored -- regenerated on demand)
 */

import { join } from "path";

const REPO_ROOT = join(import.meta.dir, "..");
const PKG_PATH = join(REPO_ROOT, "package.json");
const OUT_PATH = join(REPO_ROOT, "packages", "core", "version.ts");

const pkgText = await Bun.file(PKG_PATH).text();
const pkg = JSON.parse(pkgText) as { version?: string };
const version = pkg.version;

if (!version || typeof version !== "string" || !/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`inject-version: invalid or missing version in ${PKG_PATH}: ${version}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/inject-version.ts -- DO NOT EDIT.
// Regenerated from package.json on every \`make build-cli\` and in the
// release.yml \`build-ark\` job before \`bun build --compile\`. Baking the
// version into a TS constant avoids runtime __dirname / package.json reads
// that do not work in compiled binaries.
export const VERSION = ${JSON.stringify(version)};
`;

await Bun.write(OUT_PATH, content);
console.log(`inject-version: wrote ${OUT_PATH} (VERSION=${version})`);
